### ISSUE TITLE
Bundles vulnerable copy of Expat - please update to 2.2.4

### ISSUE THREAD

**Issue by hartwork** [luapower/expat#5]
Hi!

This repository bundles an outdated vulnerable copy of Expat 2.1.0. Please update your copy to version 2.2.1 with the latest security fixes. A change log with details is available at https://github.com/libexpat/libexpat/blob/master/expat/Changes . Thank you! 

Best

&nbsp;
Sebastian

**Comment by capr** [comment]
Thanks for the heads up. I'll update this when I have a Mac available so I can rebuild the binaries on all platforms.

**Comment by hartwork** [comment]
Any news? Expat 2.2.4 is out by now.

**Comment by hartwork** [comment]
Any news?

**Comment by capr** [comment]
You could try to update the sources and re-run the build scripts and see what would happen. Maybe it would just compile without problems out-of-the box.

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
